version: '3.6'

services:
  terraform:
    image: hashicorp/terraform:0.12.8
    container_name: terraform-eks
    volumes:
      - ./terraform:/terraform
    env_file: .env
    working_dir: /terraform
